### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by gz35yp** [wearefrank/frank-runner#87]
I am trying to start the frank runner and while starting the tomcat server, it is failing with error like "[main] org.apache.catalina.core.StandardServer.await Failed to create server shutdown socket on address [localhost] and port [8005] (base port [8005] and offset [0])
	java.net.BindException: Address already in use: JVM_Bind
		at java.net.DualStackPlainSocketImpl.bind0(Native Method)
		at java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
		at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
		at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:190)
		at java.net.ServerSocket.bind(ServerSocket.java:390)
		at java.net.ServerSocket.<init>(ServerSocket.java:252)
		at org.apache.catalina.core.StandardServer.await(StandardServer.java:580)
		at org.apache.catalina.startup.Catalina.await(Catalina.java:864)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:810)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)"

Please help on this.

**Comment by gz35yp** [comment]
The issue is resolved and Thanks for your support.

But after starting the tomcat server, Console is not opening and getting below error in logs and please find the screenshot for your reference.
" WARNING [main] org.apache.catalina.core.StandardServer.await Invalid shutdown command [GET / HTTP/1.1] received"

![Capture](https://github.com/wearefrank/frank-runner/assets/166007274/16e3930a-5ad1-446c-ad1a-c642a9291079)

**Comment by jacodg** [comment]
Hi jplreddy, the server port is not meant to be used by the user. This port is used by Tomcat itself for e.g. the stop script to signal a running Tomcat to stop. You should use the tomcat.port which by default is 80 but can also be configured to use a different port:
https://github.com/wearefrank/frank-runner?tab=readme-ov-file#other-properties-and-software-versions

**Comment by gz35yp** [comment]
Thanks for your support.

I have changed ports but, still getting same error, kindly help us.
Please find screenshot for your reference.

![image](https://github.com/wearefrank/frank-runner/assets/166007274/0c2e3923-4038-483e-b01b-4081df7730ac)

**Comment by jacodg** [comment]
Looking at your screenshot I think you have configured tomcat.port to be 90 so could you try http://localhost:90/ ?
